### ISSUE TITLE
Find most prolific Indian contributors to global OSS

### ISSUE THREAD

**Issue by ChakshuGautam** [ChakshuGautam/github-prolific-contributors#1]
## Objective

Find the most prolific Indian contributors to global OSS

## Steps
- [ ] Registry of top 1000 repos based on stars. Every repo has a score between 0-10. Possible metrics - stars, total commits (per year), total contributors, ...
- [ ] Find all contributors for those repos
- [ ] Create a profile for them and filter for India- Twitter (see some tweets) + Github (Location, URLs to other domains, portfolio) (India) + LinkendIn (public profile); Stack from the repo - languages. Twitter, GitHub, LinkedIn, and Portfolio profile links.
- [ ] Create a score for an individual between 0-10; Metrics - Total number of contributions (commits, PRs, ...), Total different repos. Reduce score for fake contributions.
- [ ] Create a DB - CSV

**Comment by KDwevedi** [comment]
sounds good

**Comment by Savio629** [comment]
:)

**Comment by KDwevedi** [comment]
## Github API Calls

https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28#get-all-contributor-commit-activity

https://docs.github.com/en/graphql/overview/explorer

**Entities:**
- Orgs
- Users
- Repos

@Savio629 
**Task:** A list of repos sorted by star count

Open Question: What contributor metrics are available publicly via API given github ID


## Profile Parsing
@shivankurchavan 
@DarrenDsouza7273 
Start with our profiles, figure out markers of nationality
**Possible Markers:**
- Github
  - Profile Description
  - Institutional Emails 
- LinkedIn
  - Education
  - WorkEx
  - Posts
- Twitter
  - Profile Description
- Portfolio

**Comment by DarrenDsouza7273** [comment]
.

**Comment by shivankurchavan** [comment]
.
